services:
  postgres:
    image: postgres:16
    container_name: s26-06-postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_s26
      POSTGRES_PASSWORD: pass_s26
      POSTGRES_DB: s26_06
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./infrastructure/database/schema.sql:/docker-entrypoint-initdb.d/01-schema.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user_s26 -d s26_06"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
